/*
 * This source file was generated by the Gradle 'init' task
 */
package org.circular;

import org.junit.jupiter.api.Test;

class CircularlyLinkedListTest {
    @Test void appHasAGreeting() {
        CircularlyLinkedList classUnderTest = new CircularlyLinkedList(); //testing done in "CircularlyLinkedList class"
    }
}
